_schema: _schema
source: /app/
paths:
  uploads: uploads
  static: ''
collections_config:
  Data (People, Additional Research, Etc.):
    path: _data
    name: Data
    icon: list
    disable_url: true
    description: ''
    _enabled_editors:
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
  Draft Blog Posts:
    path: _drafts
    name: Drafts
    icon: psychology_alt
    disable_url: false
    description: ''
    _enabled_editors:
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.posts[*].tags
        cascade: true
    create:
      path: ''
      publish_to: posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  Blog Posts:
    path: _posts
    name: Posts
    icon: newspaper
    disable_url: false
    description: ''
    _enabled_editors:
    _inputs:
      categories:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.posts[*].categories
        cascade: true
      tags:
        type: multiselect
        options:
          allow_create: true
          empty_type: array
          values: collections.posts[*].tags
        cascade: true
    add_options:
      - name: Add Post
      - name: Add Draft
        collection: drafts
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  Events:
    path: _events
    name: Events
    icon: event
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  Jobs:
    path: _jobs
    name: Jobs
    icon: person_search
    disable_url: true
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  Our Work (listed, but no project page):
    path: _our_work_pageless
    name: Our Work Pageless
    icon: work_off
    disable_url: true
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  Our Work:
    path: _our_work
    name: Our Work
    icon: work_outline
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  Other Pages:
    path: ''
    name: Other Pages (Home, About, 404, etc.)
    icon: toc
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_snippets_imports:
  eleventy_liquid: true
timezone: America/New_York
markdown:
  engine: commonmark
  options:
    html: true
    linkify: true
    typographer: true