version: 2.1
jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project

      - run:
          name: "Info"
          command: |
            docker-compose --version
            docker version
            npm --version

      - restore_cache:
          keys:
            - bundle-{{ checksum "app/Gemfile.lock" }}

      - run:
          name: "Setup"
          command: |
            npm install vnu-jar
            sudo mkdir -m 777 build
            ls bundle || sudo mkdir -m 777 bundle
            sudo mkdir -m 777 app/.jekyll-cache

      - run:
          name: "Test"
          command: |
            bash ./scripts/run-tests.sh

      - save_cache:
          key: bundle-{{ checksum "app/Gemfile.lock" }}
          paths:
            - bundle

      - run:
          name: "Deploy"
          command: |
            if [[ "$CIRCLE_PULL_REQUEST" == "" && "$CIRCLE_BRANCH" == "develop" ]] ; then
                export DEPLOY_CONTENT='{"CIRCLE_BUILD_NUM":"'$CIRCLE_BUILD_NUM'","CIRCLE_SHA1":"'$CIRCLE_SHA1'","CIRCLE_BRANCH":"'$CIRCLE_BRANCH'","CIRCLE_PROJECT_REPONAME":"'$CIRCLE_PROJECT_REPONAME'","CIRCLE_PROJECT_USERNAME":"'$CIRCLE_PROJECT_USERNAME'"}' ;
                export DEPLOY_SIG="sha1=`echo -n "$DEPLOY_CONTENT" | openssl sha1 -hmac $DEPLOY_KEY | sed 's/^.* //'`" ;
                curl -X POST "$DEPLOY_URL" --data "$DEPLOY_CONTENT" -H "Content-Type: application/json" -H "X-Circle-Signature: $DEPLOY_SIG" ;
            fi
