name: Build and Deploy to S3

on:
  workflow_dispatch

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.10' # Match your Gemfile/Gemfile.lock

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: JEKYLL_ENV=production bundle exec jekyll build --trace

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::915821419033:role/github-actions
          aws-region: us-east-1

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'build'

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'